#Config

open_api_key: "sk-0000"
csv_path: "C:\\Users\\Lydus\\QUIQ_table.csv"

#Accuracy
maximum_class_n: 10

#Voca_consistency
show_details: True

#Time_consistency
mul: 2
min_percentile: 10
min_patient_count: 100

#Word_diversity & Sentence_diversity
top_n: 10
