openai_api_key: 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
csv_path: /Users/songsoo/Library/CloudStorage/OneDrive-개인/0. Ongoing/리더스/리더스 데이터구조 표준화/패키지화/충실성 판독문/fidelity_radiology/표준구조 예시.csv
variable_name: head ct
