General_session_id: 1
General_table_name: 20231021_lab_total_table_total.csv
신뢰도_operation_type: automatic
신뢰도_automatic_num: 10
신뢰도_target_variable: Creatinine
신뢰도_gpt_model_type: gpt-4
신뢰도_recommended_variable_num: 7
신뢰도_splitnum: 2
신뢰도_hidden_length1: 5
신뢰도_hidden_length2: 4
신뢰도_openai_key: enter_api_key
범위유효성_boxplotnum: 10