#main 
csv_path: "/Users/Desktop/QUIQ_table.csv"
VIA_path: "/Users/Desktop/VIA_table.csv"
save_path: "/Users/Desktop/LYDUS"
open_api_key: sk-0000

#신뢰도(Reliability)
Reliability_operation_type: manual
Reliability_automatic_num: 2
Reliability_target_variable: Creatinine
Reliability_gpt_model_type: gpt-4
Reliability_recommended_variable_num: 7

#정확도, 정밀도, 재현율, F1, AUROC(Accuracy) 
Accuracy_maximum_class_n: 10

#범위 유효성(RangeValidity)
Rangevalidity_boxplotnum: 10

#단면적 일관성(Voca_consistency)
Voca_consistency_show_details: True

#시계열적 일관성(Time_consistency)
Time_consistency_mul: 2
Time_consistency_min_percentile: 10
Time_consistency_min_patient_count: 100

#문장의 다양성/어휘의 다양성 (Text_diversity) 
Text_diversity_top_n: 10
