General_session_id: 1
General_table_name: 20240223_df_standard_concat.csv
Reliability_operation_type: manual
Reliability_automatic_num: 1
Reliability_target_variable: Creatinine
Reliability_gpt_model_type: gpt-4
Reliability_recommended_variable_num: 7
Reliability_openai_key: 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
